name: Cmake build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup cmake
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake valgrind
          pip install ValgrindCI
          gcc --version
          cmake --version
          ninja --version
          valgrind --version
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.OS }}-build-cache
      - name: Setup project build system
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build -j
      - name: Tests with Valgrind
        run: |
          valgrind --tool=memcheck --xml=yes --xml-file=unit_tests_valgrind.xml --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./build/test/engine-tests --gtest_filter="*" --gtest_color=no
          valgrind-ci unit_tests_valgrind.xml --summary
          valgrind-ci unit_tests_valgrind.xml --abort-on-errors
